#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.19kB done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.10
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/6] FROM docker.io/library/python:3.10
#4 DONE 0.0s

#5 [2/6] RUN mkdir -p ~/.pip && touch ~/.pip/pip.conf &&     echo "[global]" >> ~/.pip/pip.conf && echo "index-url=http://simple/" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.conf && echo "trusted-host=pypi..org" >> ~/.pip/pip.conf &&     apt-get update && apt-get install -y curl &&     curl -sSL https://install.python-poetry.org | python -
#5 CACHED

#6 [3/6] RUN pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/ib-api-reloaded/ib_async.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /ib_async/. /repo && rm -rf /ib_async/ &&     rm -rf /ib_async &&     cd /repo && git checkout 38cf54a66a4daefbd3fd1d7476381f0d178a8198 &&     cd /repo && poetry install
#6 1.840 Looking in indexes: http://simple/
#6 1.995 Collecting pytest
#6 2.018   Downloading http://packages/pytest/pytest-8.3.4-py3-none-any.whl (343 kB)
#6 2.038      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.1/343.1 kB 22.3 MB/s eta 0:00:00
#6 2.109 Collecting pytest-xdist
#6 2.128   Downloading http://packages/pytest-xdist/pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
#6 2.139      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 4.6 MB/s eta 0:00:00
#6 2.213 Collecting tomli>=1
#6 2.232   Downloading http://packages/tomli/tomli-2.2.1-py3-none-any.whl (14 kB)
#6 2.265 Collecting iniconfig
#6 2.282   Downloading http://packages/iniconfig/iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
#6 2.328 Collecting pluggy<2,>=1.5
#6 2.346   Downloading http://packages/pluggy/pluggy-1.5.0-py3-none-any.whl (20 kB)
#6 2.409 Collecting packaging
#6 2.432   Downloading http://packages/packaging/packaging-24.2-py3-none-any.whl (65 kB)
#6 2.444      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 7.0 MB/s eta 0:00:00
#6 2.487 Collecting exceptiongroup>=1.0.0rc8
#6 2.505   Downloading http://packages/exceptiongroup/exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
#6 2.575 Collecting execnet>=2.1
#6 2.593   Downloading http://packages/execnet/execnet-2.1.1-py3-none-any.whl (40 kB)
#6 2.601      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 7.9 MB/s eta 0:00:00
#6 2.717 Installing collected packages: tomli, pluggy, packaging, iniconfig, execnet, exceptiongroup, pytest, pytest-xdist
#6 3.247 Successfully installed exceptiongroup-1.2.2 execnet-2.1.1 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pytest-8.3.4 pytest-xdist-3.6.1 tomli-2.2.1
#6 3.248 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 3.388 
#6 3.388 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
#6 3.388 [notice] To update, run: pip install --upgrade pip
#6 4.102 Looking in indexes: http://simple/
#6 4.184 Collecting pipdeptree
#6 4.207   Downloading http://packages/pipdeptree/pipdeptree-2.24.0-py3-none-any.whl (32 kB)
#6 4.231 Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.10/site-packages (from pipdeptree) (24.2)
#6 4.350 Collecting pip>=24.2
#6 4.363   Using cached http://packages/pip/pip-24.3.1-py3-none-any.whl (1.8 MB)
#6 4.494 Installing collected packages: pip, pipdeptree
#6 4.494   Attempting uninstall: pip
#6 4.495     Found existing installation: pip 23.0.1
#6 4.661     Uninstalling pip-23.0.1:
#6 4.813       Successfully uninstalled pip-23.0.1
#6 6.091 Successfully installed pip-24.3.1 pipdeptree-2.24.0
#6 6.092 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 6.265 Cloning into 'ib_async'...
#6 15.58 Note: switching to '38cf54a66a4daefbd3fd1d7476381f0d178a8198'.
#6 15.58 
#6 15.58 You are in 'detached HEAD' state. You can look around, make experimental
#6 15.58 changes and commit them, and you can discard any commits you make in this
#6 15.58 state without impacting any branches by switching back to a branch.
#6 15.58 
#6 15.58 If you want to create a new branch to retain commits you create, you may
#6 15.58 do so (now or later) by using -c with the switch command. Example:
#6 15.58 
#6 15.58   git switch -c <new-branch-name>
#6 15.58 
#6 15.58 Or undo this operation with:
#6 15.58 
#6 15.58   git switch -
#6 15.58 
#6 15.58 Turn off this advice by setting config variable advice.detachedHead to false
#6 15.58 
#6 15.58 HEAD is now at 38cf54a Fix type warnings due to mypy version update
#6 16.70 Creating virtualenv ib-async-gW_DSdP6-py3.10 in /root/.cache/pypoetry/virtualenvs
#6 17.95 Updating dependencies
#6 17.95 Resolving dependencies...
#6 39.02 
#6 39.02 Package operations: 3 installs, 0 updates, 0 removals
#6 39.02 
#6 39.02   - Installing numpy (2.2.1)
#6 41.15   - Installing eventkit (1.0.3)
#6 41.15   - Installing nest-asyncio (1.6.0)
#6 41.79 
#6 41.79 Writing lock file
#6 41.79 
#6 41.79 Installing the current project: ib_async (1.0.3)
#6 DONE 42.7s

#7 [4/6] RUN pip install eventkit==1.0.3 &&     pip install -e /repo &&     pip install pandas==2.2.3
#7 1.061 Looking in indexes: http://simple/
#7 1.194 Collecting eventkit==1.0.3
#7 1.310   Downloading http://packages/eventkit/eventkit-1.0.3-py3-none-any.whl (31 kB)
#7 1.729 Collecting numpy (from eventkit==1.0.3)
#7 1.753   Downloading http://packages/numpy/numpy-2.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
#7 1.866      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 176.5 MB/s eta 0:00:00
#7 1.977 Installing collected packages: numpy, eventkit
#7 4.813 Successfully installed eventkit-1.0.3 numpy-2.2.1
#7 4.814 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#7 5.612 Looking in indexes: http://simple/
#7 5.612 Obtaining file:///repo
#7 5.617   Installing build dependencies: started
#7 6.798   Installing build dependencies: finished with status 'done'
#7 6.800   Checking if build backend supports build_editable: started
#7 6.934   Checking if build backend supports build_editable: finished with status 'done'
#7 6.937   Getting requirements to build editable: started
#7 7.071   Getting requirements to build editable: finished with status 'done'
#7 7.072   Preparing editable metadata (pyproject.toml): started
#7 7.372   Preparing editable metadata (pyproject.toml): finished with status 'done'
#7 7.386 Requirement already satisfied: eventkit in /usr/local/lib/python3.10/site-packages (from ib_async==1.0.3) (1.0.3)
#7 7.445 Collecting nest_asyncio (from ib_async==1.0.3)
#7 7.476   Downloading http://packages/nest-asyncio/nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
#7 7.497 Requirement already satisfied: numpy in /usr/local/lib/python3.10/site-packages (from eventkit->ib_async==1.0.3) (2.2.1)
#7 7.504 Building wheels for collected packages: ib_async
#7 7.509   Building editable for ib_async (pyproject.toml): started
#7 7.914   Building editable for ib_async (pyproject.toml): finished with status 'done'
#7 7.914   Created wheel for ib_async: filename=ib_async-1.0.3-py3-none-any.whl size=5064 sha256=bb4a5c907dd9fbfc54dca97c50aa1fd4b8af7f5ffeda4baf4e12cbb327ba0bff
#7 7.918   Stored in directory: /tmp/pip-ephem-wheel-cache-y4a3nt77/wheels/83/05/69/977b54e69478800cfcea8a9437a7ea4a9b1a48db334f824611
#7 7.950 Successfully built ib_async
#7 7.975 Installing collected packages: nest_asyncio, ib_async
#7 8.055 Successfully installed ib_async-1.0.3 nest_asyncio-1.6.0
#7 8.066 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#7 9.007 Looking in indexes: http://simple/
#7 9.350 Collecting pandas==2.2.3
#7 9.377   Downloading http://packages/pandas/pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
#7 9.480      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 149.1 MB/s eta 0:00:00
#7 9.606 Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/site-packages (from pandas==2.2.3) (2.2.1)
#7 9.637 Collecting python-dateutil>=2.8.2 (from pandas==2.2.3)
#7 9.656   Downloading http://packages/python-dateutil/python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
#7 9.798 Collecting pytz>=2020.1 (from pandas==2.2.3)
#7 9.818   Downloading http://packages/pytz/pytz-2024.2-py2.py3-none-any.whl (508 kB)
#7 9.896 Collecting tzdata>=2022.7 (from pandas==2.2.3)
#7 9.915   Downloading http://packages/tzdata/tzdata-2024.2-py2.py3-none-any.whl (346 kB)
#7 9.981 Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.2.3)
#7 10.00   Downloading http://packages/six/six-1.17.0-py2.py3-none-any.whl (11 kB)
#7 10.13 Installing collected packages: pytz, tzdata, six, python-dateutil, pandas
#7 16.51 Successfully installed pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 six-1.17.0 tzdata-2024.2
#7 16.51 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#7 DONE 17.2s

#8 [5/6] RUN cd /repo && pytest --collect-only -q
#8 1.693 tests/test_contract.py::test_contract_format_data_pd
#8 1.693 tests/test_requests.py::test_request_error_raised
#8 1.693 tests/test_requests.py::test_account_summary
#8 1.693 
#8 1.693 =============================== warnings summary ===============================
#8 1.693 ../usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py:1441
#8 1.693   /usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py:1441: PytestConfigWarning: Unknown config option: asyncio_mode
#8 1.693   
#8 1.693     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
#8 1.693 
#8 1.693 tests/test_requests.py:5
#8 1.693   /repo/tests/test_requests.py:5: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
#8 1.693     pytestmark = pytest.mark.asyncio
#8 1.693 
#8 1.693 -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
#8 1.693 3 tests collected in 0.35s
#8 DONE 2.0s

#9 exporting to image
#9 exporting layers
#9 exporting layers 1.5s done
#9 writing image sha256:572c3c4364a7873986cc60a3b4bfe830d6794524665ad9eb49b0cf4625365952 done
#9 naming to docker.io/library/tmp:tmp done
#9 DONE 1.5s
