#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile:
#1 transferring dockerfile: 1.07kB done
#1 DONE 3.4s

#2 [internal] load metadata for docker.io/library/python:3.10
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/5] FROM docker.io/library/python:3.10
#4 DONE 0.0s

#5 [2/5] RUN mkdir -p ~/.pip && touch ~/.pip/pip.conf &&     echo "[global]" >> ~/.pip/pip.conf && echo "index-url=http://simple/" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.conf && echo "trusted-host=pypi..org" >> ~/.pip/pip.conf &&     apt-get update && apt-get install -y curl &&     curl -sSL https://install.python-poetry.org | python -
#5 CACHED

#6 [3/5] RUN pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/a-s-g93/neo4j-runway.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /neo4j-runway/. /repo && rm -rf /neo4j-runway/ &&     rm -rf /neo4j-runway &&     cd /repo && git checkout 16b44177d434465f7fbeef59273444c963343726 &&     cd /repo && poetry install
#6 1.655 Looking in indexes: http://simple/
#6 1.811 Collecting pytest
#6 1.829   Downloading http://packages/pytest/pytest-8.3.4-py3-none-any.whl (343 kB)
#6 1.845      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.1/343.1 kB 32.2 MB/s eta 0:00:00
#6 1.930 Collecting pytest-xdist
#6 1.947   Downloading http://packages/pytest-xdist/pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
#6 1.956      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 8.6 MB/s eta 0:00:00
#6 2.038 Collecting packaging
#6 2.057   Downloading http://packages/packaging/packaging-24.2-py3-none-any.whl (65 kB)
#6 2.066      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 11.1 MB/s eta 0:00:00
#6 2.094 Collecting iniconfig
#6 2.112   Downloading http://packages/iniconfig/iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
#6 2.161 Collecting pluggy<2,>=1.5
#6 2.180   Downloading http://packages/pluggy/pluggy-1.5.0-py3-none-any.whl (20 kB)
#6 2.230 Collecting exceptiongroup>=1.0.0rc8
#6 2.260   Downloading http://packages/exceptiongroup/exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
#6 2.321 Collecting tomli>=1
#6 2.338   Downloading http://packages/tomli/tomli-2.2.1-py3-none-any.whl (14 kB)
#6 2.408 Collecting execnet>=2.1
#6 2.425   Downloading http://packages/execnet/execnet-2.1.1-py3-none-any.whl (40 kB)
#6 2.433      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 7.5 MB/s eta 0:00:00
#6 2.553 Installing collected packages: tomli, pluggy, packaging, iniconfig, execnet, exceptiongroup, pytest, pytest-xdist
#6 3.080 Successfully installed exceptiongroup-1.2.2 execnet-2.1.1 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pytest-8.3.4 pytest-xdist-3.6.1 tomli-2.2.1
#6 3.081 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 3.202 
#6 3.202 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
#6 3.202 [notice] To update, run: pip install --upgrade pip
#6 3.882 Looking in indexes: http://simple/
#6 3.957 Collecting pipdeptree
#6 3.976   Downloading http://packages/pipdeptree/pipdeptree-2.24.0-py3-none-any.whl (32 kB)
#6 4.106 Collecting pip>=24.2
#6 4.117   Using cached http://packages/pip/pip-24.3.1-py3-none-any.whl (1.8 MB)
#6 4.135 Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.10/site-packages (from pipdeptree) (24.2)
#6 4.244 Installing collected packages: pip, pipdeptree
#6 4.245   Attempting uninstall: pip
#6 4.246     Found existing installation: pip 23.0.1
#6 4.406     Uninstalling pip-23.0.1:
#6 4.557       Successfully uninstalled pip-23.0.1
#6 5.751 Successfully installed pip-24.3.1 pipdeptree-2.24.0
#6 5.751 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 5.911 Cloning into 'neo4j-runway'...
#6 9.809 Note: switching to '16b44177d434465f7fbeef59273444c963343726'.
#6 9.809 
#6 9.809 You are in 'detached HEAD' state. You can look around, make experimental
#6 9.809 changes and commit them, and you can discard any commits you make in this
#6 9.809 state without impacting any branches by switching back to a branch.
#6 9.809 
#6 9.809 If you want to create a new branch to retain commits you create, you may
#6 9.809 do so (now or later) by using -c with the switch command. Example:
#6 9.809 
#6 9.809   git switch -c <new-branch-name>
#6 9.809 
#6 9.809 Or undo this operation with:
#6 9.809 
#6 9.809   git switch -
#6 9.809 
#6 9.809 Turn off this advice by setting config variable advice.detachedHead to false
#6 9.809 
#6 9.809 HEAD is now at 16b4417 Create data dictionary class (#148)
#6 10.82 Creating virtualenv neo4j-runway-gW_DSdP6-py3.10 in /root/.cache/pypoetry/virtualenvs
#6 11.89 Installing dependencies from lock file
#6 12.46 
#6 12.46 Package operations: 109 installs, 0 updates, 0 removals
#6 12.46 
#6 12.46   - Installing attrs (24.2.0)
#6 12.46   - Installing rpds-py (0.20.0)
#6 14.14   - Installing referencing (0.35.1)
#6 14.39   - Installing certifi (2024.8.30)
#6 14.40   - Installing exceptiongroup (1.2.2)
#6 14.40   - Installing h11 (0.14.0)
#6 14.40   - Installing idna (3.10)
#6 14.40   - Installing jsonschema-specifications (2024.10.1)
#6 14.41   - Installing mdurl (0.1.2)
#6 14.41   - Installing platformdirs (4.3.6)
#6 14.41   - Installing six (1.16.0)
#6 14.42   - Installing sniffio (1.3.1)
#6 14.42   - Installing traitlets (5.14.3)
#6 14.42   - Installing typing-extensions (4.12.2)
#6 15.73   - Installing annotated-types (0.7.0)
#6 15.73   - Installing anyio (4.6.2.post1)
#6 15.73   - Installing asttokens (2.4.1)
#6 15.74   - Installing executing (2.1.0)
#6 15.74   - Installing frozenlist (1.5.0)
#6 15.75   - Installing fastjsonschema (2.20.0)
#6 15.75   - Installing jupyter-core (5.7.2)
#6 15.75   - Installing jsonschema (4.23.0)
#6 15.76   - Installing multidict (6.1.0)
#6 15.76   - Installing parso (0.8.4)
#6 15.77   - Installing ptyprocess (0.7.0)
#6 15.77   - Installing pure-eval (0.2.3)
#6 15.77   - Installing httpcore (1.0.6)
#6 15.77   - Installing pygments (2.18.0)
#6 15.78   - Installing python-dateutil (2.9.0.post0)
#6 15.78   - Installing pydantic-core (2.23.4)
#6 15.78   - Installing wcwidth (0.2.13)
#6 15.78   - Installing markdown-it-py (3.0.0)
#6 15.79   - Installing tornado (6.4.1)
#6 15.79   - Installing pyzmq (26.2.0)
#6 15.79   - Installing propcache (0.2.0)
#6 18.10   - Installing aiohappyeyeballs (2.4.3)
#6 18.10   - Installing aiosignal (1.3.1)
#6 18.10   - Installing async-timeout (4.0.3)
#6 18.10   - Installing decorator (5.1.1)
#6 18.11   - Installing click (8.1.7)
#6 18.11   - Installing distlib (0.3.9)
#6 18.11   - Installing distro (1.9.0)
#6 18.12   - Installing filelock (3.16.1)
#6 18.12   - Installing httpx (0.27.2)
#6 18.12   - Installing jedi (0.19.1)
#6 18.13   - Installing iniconfig (2.0.0)
#6 18.13   - Installing markupsafe (3.0.2)
#6 18.13   - Installing matplotlib-inline (0.1.7)
#6 18.14   - Installing packaging (24.1)
#6 18.14   - Installing pexpect (4.9.0)
#6 18.14   - Installing jiter (0.5.0)
#6 18.14   - Installing nbformat (5.10.4)
#6 18.15   - Installing rich (13.9.3)
#6 18.15   - Installing pluggy (1.5.0)
#6 18.15   - Installing pydantic (2.9.2)
#6 18.15   - Installing jupyter-client (8.6.3)
#6 18.16   - Installing soupsieve (2.6)
#6 18.16   - Installing prompt-toolkit (3.0.48)
#6 18.17   - Installing shellingham (1.5.4)
#6 18.17   - Installing tqdm (4.66.5)
#6 18.17   - Installing webencodings (0.5.1)
#6 18.17   - Installing yarl (1.16.0)
#6 18.18   - Installing tomli (2.0.2)
#6 18.18   - Installing stack-data (0.6.3)
#6 20.42   - Installing aiohttp (3.10.10)
#6 20.42   - Installing beautifulsoup4 (4.12.3)
#6 20.42   - Installing bleach (6.1.0)
#6 20.42   - Installing cfgv (3.4.0)
#6 20.42   - Installing comm (0.2.2)
#6 20.43   - Installing debugpy (1.8.7)
#6 20.43   - Installing defusedxml (0.7.1)
#6 20.43   - Installing docstring-parser (0.16)
#6 20.43   - Installing identify (2.6.1)
#6 20.44   - Installing ipython (8.28.0)
#6 20.44   - Installing jinja2 (3.1.4)
#6 20.44   - Installing jupyterlab-pygments (0.3.0)
#6 20.45   - Installing mistune (3.0.2)
#6 20.45   - Installing mypy-extensions (1.0.0)
#6 20.45   - Installing nbclient (0.10.0)
#6 20.45   - Installing nest-asyncio (1.6.0)
#6 20.45   - Installing nodeenv (1.9.1)
#6 20.46   - Installing numpy (1.26.4)
#6 20.46   - Installing openai (1.52.2)
#6 20.46   - Installing pandocfilters (1.5.1)
#6 20.47   - Installing psutil (6.1.0)
#6 20.47   - Installing pytest (8.3.3)
#6 20.47   - Installing pytz (2024.2)
#6 20.47   - Installing tenacity (8.5.0)
#6 20.48   - Installing pyyaml (6.0.2)
#6 20.48   - Installing tinycss2 (1.4.0)
#6 20.48   - Installing typer (0.12.5)
#6 20.48   - Installing tzdata (2024.2)
#6 20.49   - Installing virtualenv (20.27.0)
#6 26.68   - Installing coverage (7.6.4)
#6 26.69   - Installing graphviz (0.20.3)
#6 26.69   - Installing instructor (1.5.2)
#6 26.70   - Installing ipykernel (6.29.5)
#6 26.70   - Installing nbconvert (7.16.4)
#6 26.71   - Installing pandas (2.2.3)
#6 26.71   - Installing pre-commit (3.8.0)
#6 26.71   - Installing neo4j (5.25.0)
#6 26.72   - Installing python-dotenv (1.0.1)
#6 26.72   - Installing pytest-mock (3.14.0)
#6 26.72   - Installing mypy (1.13.0)
#6 26.73   - Installing toml (0.10.2)
#6 26.73   - Installing types-pyyaml (6.0.12.20240917)
#6 26.73   - Installing tabulate (0.9.0)
#6 26.73   - Installing ruff (0.3.7)
#6 26.74   - Installing regex (2024.9.11)
#6 30.67 
#6 30.67 Installing the current project: neo4j-runway (0.14.0)
#6 DONE 33.1s

#7 [4/5] RUN cd /repo && pytest --collect-only -q
#7 2.312 
#7 2.312 ==================================== ERRORS ====================================
#7 2.312 ____________ ERROR collecting neo4j_runway/utils/test_connection.py ____________
#7 2.312 ImportError while importing test module '/repo/neo4j_runway/utils/test_connection.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/integration/code_generation/load_csv/test_load_csv_via_api_IT.py _
#7 2.312 ImportError while importing test module '/repo/tests/integration/code_generation/load_csv/test_load_csv_via_api_IT.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/integration/code_generation/load_csv/test_load_csv_via_api_IT.py:4: in <module>
#7 2.312     from dotenv import load_dotenv
#7 2.312 E   ModuleNotFoundError: No module named 'dotenv'
#7 2.312 _ ERROR collecting tests/integration/code_generation/load_csv/test_load_csv_via_api_multi_csv_IT.py _
#7 2.312 ImportError while importing test module '/repo/tests/integration/code_generation/load_csv/test_load_csv_via_api_multi_csv_IT.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/integration/code_generation/load_csv/test_load_csv_via_api_multi_csv_IT.py:4: in <module>
#7 2.312     from dotenv import load_dotenv
#7 2.312 E   ModuleNotFoundError: No module named 'dotenv'
#7 2.312 _ ERROR collecting tests/integration/code_generation/load_csv/test_load_csv_via_api_multi_csv_and_same_node_rel_IT.py _
#7 2.312 ImportError while importing test module '/repo/tests/integration/code_generation/load_csv/test_load_csv_via_api_multi_csv_and_same_node_rel_IT.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/integration/code_generation/load_csv/test_load_csv_via_api_multi_csv_and_same_node_rel_IT.py:4: in <module>
#7 2.312     from dotenv import load_dotenv
#7 2.312 E   ModuleNotFoundError: No module named 'dotenv'
#7 2.312 _ ERROR collecting tests/integration/code_generation/load_csv/test_load_csv_via_api_node_keys_IT.py _
#7 2.312 ImportError while importing test module '/repo/tests/integration/code_generation/load_csv/test_load_csv_via_api_node_keys_IT.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/integration/code_generation/load_csv/test_load_csv_via_api_node_keys_IT.py:4: in <module>
#7 2.312     from dotenv import load_dotenv
#7 2.312 E   ModuleNotFoundError: No module named 'dotenv'
#7 2.312 ______ ERROR collecting tests/integration/database/test_neo4j_graph_IT.py ______
#7 2.312 ImportError while importing test module '/repo/tests/integration/database/test_neo4j_graph_IT.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/integration/database/test_neo4j_graph_IT.py:4: in <module>
#7 2.312     from neo4j_runway.database import Neo4jGraph
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _________________ ERROR collecting tests/integration/discovery _________________
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 <frozen importlib._bootstrap>:1050: in _gcd_import
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:1027: in _find_and_load
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:688: in _load_unlocked
#7 2.312     ???
#7 2.312 /usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
#7 2.312     exec(co, module.__dict__)
#7 2.312 tests/integration/discovery/conftest.py:3: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _________________ ERROR collecting tests/integration/graph_eda _________________
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 <frozen importlib._bootstrap>:1050: in _gcd_import
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:1027: in _find_and_load
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:688: in _load_unlocked
#7 2.312     ???
#7 2.312 /usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
#7 2.312     exec(co, module.__dict__)
#7 2.312 tests/integration/graph_eda/conftest.py:3: in <module>
#7 2.312     import neo4j
#7 2.312 E   ModuleNotFoundError: No module named 'neo4j'
#7 2.312 __ ERROR collecting tests/integration/ingestion/test_pyingest_dataframe_IT.py __
#7 2.312 ImportError while importing test module '/repo/tests/integration/ingestion/test_pyingest_dataframe_IT.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/integration/ingestion/test_pyingest_dataframe_IT.py:4: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 __ ERROR collecting tests/integration/ingestion/test_pyingest_multi_csv_IT.py __
#7 2.312 ImportError while importing test module '/repo/tests/integration/ingestion/test_pyingest_multi_csv_IT.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/integration/ingestion/test_pyingest_multi_csv_IT.py:4: in <module>
#7 2.312     from dotenv import load_dotenv
#7 2.312 E   ModuleNotFoundError: No module named 'dotenv'
#7 2.312 _ ERROR collecting tests/integration/ingestion/test_pyingest_post_ingestion_IT.py _
#7 2.312 ImportError while importing test module '/repo/tests/integration/ingestion/test_pyingest_post_ingestion_IT.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/integration/ingestion/test_pyingest_post_ingestion_IT.py:4: in <module>
#7 2.312     from dotenv import load_dotenv
#7 2.312 E   ModuleNotFoundError: No module named 'dotenv'
#7 2.312 __________________ ERROR collecting tests/integration/modeler __________________
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 <frozen importlib._bootstrap>:1050: in _gcd_import
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:1027: in _find_and_load
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:688: in _load_unlocked
#7 2.312     ???
#7 2.312 /usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
#7 2.312     exec(co, module.__dict__)
#7 2.312 tests/integration/modeler/conftest.py:5: in <module>
#7 2.312     from neo4j_runway.discovery.discovery import Discovery
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 ________________ ERROR collecting tests/integration/utils/data _________________
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 <frozen importlib._bootstrap>:1050: in _gcd_import
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:1027: in _find_and_load
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
#7 2.312     ???
#7 2.312 <frozen importlib._bootstrap>:688: in _load_unlocked
#7 2.312     ???
#7 2.312 /usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
#7 2.312     exec(co, module.__dict__)
#7 2.312 tests/integration/utils/data/conftest.py:1: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/unit/code_generation/cypher/test_cypher_generation.py _
#7 2.312 ImportError while importing test module '/repo/tests/unit/code_generation/cypher/test_cypher_generation.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/unit/code_generation/cypher/test_cypher_generation.py:3: in <module>
#7 2.312     from neo4j_runway.code_generation.cypher import (
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/unit/code_generation/cypher/test_cypher_generation_class.py _
#7 2.312 ImportError while importing test module '/repo/tests/unit/code_generation/cypher/test_cypher_generation_class.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/unit/code_generation/cypher/test_cypher_generation_class.py:1: in <module>
#7 2.312     from neo4j_runway import DataModel
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/unit/code_generation/load_csv/test_load_csv_generation.py _
#7 2.312 ImportError while importing test module '/repo/tests/unit/code_generation/load_csv/test_load_csv_generation.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/unit/code_generation/load_csv/test_load_csv_generation.py:1: in <module>
#7 2.312     from neo4j_runway import DataModel
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/unit/code_generation/pyingest/test_pyingest_generation_multi_csv.py _
#7 2.312 ImportError while importing test module '/repo/tests/unit/code_generation/pyingest/test_pyingest_generation_multi_csv.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/unit/code_generation/pyingest/test_pyingest_generation_multi_csv.py:3: in <module>
#7 2.312     from neo4j_runway.code_generation import PyIngestConfigGenerator
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/unit/code_generation/pyingest/test_pyingest_generation_wht_params.py _
#7 2.312 ImportError while importing test module '/repo/tests/unit/code_generation/pyingest/test_pyingest_generation_wht_params.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/unit/code_generation/pyingest/test_pyingest_generation_wht_params.py:3: in <module>
#7 2.312     from neo4j_runway.code_generation import PyIngestConfigGenerator
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/unit/code_generation/pyingest/test_pyingest_generation_with_params.py _
#7 2.312 ImportError while importing test module '/repo/tests/unit/code_generation/pyingest/test_pyingest_generation_with_params.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/unit/code_generation/pyingest/test_pyingest_generation_with_params.py:3: in <module>
#7 2.312     from neo4j_runway.code_generation import PyIngestConfigGenerator
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/unit/code_generation/pyingest/test_pyingest_post_ingest_input.py _
#7 2.312 ImportError while importing test module '/repo/tests/unit/code_generation/pyingest/test_pyingest_post_ingest_input.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/unit/code_generation/pyingest/test_pyingest_post_ingest_input.py:4: in <module>
#7 2.312     from neo4j_runway.code_generation import PyIngestConfigGenerator
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/unit/code_generation/pyingest/test_pyingest_pre_ingest_input.py _
#7 2.312 ImportError while importing test module '/repo/tests/unit/code_generation/pyingest/test_pyingest_pre_ingest_input.py'.
#7 2.312 Hint: make sure your test modules/packages have valid Python names.
#7 2.312 Traceback:
#7 2.312 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.312     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.312 tests/unit/code_generation/pyingest/test_pyingest_pre_ingest_input.py:4: in <module>
#7 2.312     from neo4j_runway.code_generation import PyIngestConfigGenerator
#7 2.312 neo4j_runway/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.312     from .discovery import Discovery
#7 2.312 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.312     import pandas as pd
#7 2.312 E   ModuleNotFoundError: No module named 'pandas'
#7 2.312 _ ERROR collecting tests/unit/code_generation/standard/test_standard_code_generator.py _
#7 2.313 ImportError while importing test module '/repo/tests/unit/code_generation/standard/test_standard_code_generator.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/code_generation/standard/test_standard_code_generator.py:4: in <module>
#7 2.313     from neo4j_runway.code_generation import StandardCypherCodeGenerator
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 ____________________ ERROR collecting tests/unit/discovery _____________________
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 <frozen importlib._bootstrap>:1050: in _gcd_import
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:1027: in _find_and_load
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:688: in _load_unlocked
#7 2.313     ???
#7 2.313 /usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
#7 2.313     exec(co, module.__dict__)
#7 2.313 tests/unit/discovery/conftest.py:5: in <module>
#7 2.313     from neo4j_runway.llm.openai.discovery import OpenAIDiscoveryLLM
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 ____________________ ERROR collecting tests/unit/graph_eda _____________________
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 <frozen importlib._bootstrap>:1050: in _gcd_import
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:1027: in _find_and_load
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:688: in _load_unlocked
#7 2.313     ???
#7 2.313 /usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
#7 2.313     exec(co, module.__dict__)
#7 2.313 tests/unit/graph_eda/conftest.py:5: in <module>
#7 2.313     from neo4j_runway.database.neo4j import Neo4jGraph
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 ____________ ERROR collecting tests/unit/inputs/test_user_input.py _____________
#7 2.313 ImportError while importing test module '/repo/tests/unit/inputs/test_user_input.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/inputs/test_user_input.py:3: in <module>
#7 2.313     from neo4j_runway.inputs import UserInput, user_input_safe_construct
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _______________ ERROR collecting tests/unit/llm/test_context.py ________________
#7 2.313 ImportError while importing test module '/repo/tests/unit/llm/test_context.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/llm/test_context.py:3: in <module>
#7 2.313     from neo4j_runway.llm.context import Context, create_context
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _____________________ ERROR collecting tests/unit/modeler ______________________
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 <frozen importlib._bootstrap>:1050: in _gcd_import
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:1027: in _find_and_load
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:688: in _load_unlocked
#7 2.313     ???
#7 2.313 /usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
#7 2.313     exec(co, module.__dict__)
#7 2.313 tests/unit/modeler/conftest.py:5: in <module>
#7 2.313     from neo4j_runway.discovery import Discovery
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _____ ERROR collecting tests/unit/models/arrows/test_arrows_data_model.py ______
#7 2.313 ImportError while importing test module '/repo/tests/unit/models/arrows/test_arrows_data_model.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/models/arrows/test_arrows_data_model.py:5: in <module>
#7 2.313     from neo4j_runway.models import (
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 ___________________ ERROR collecting tests/unit/models/core ____________________
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 <frozen importlib._bootstrap>:1050: in _gcd_import
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:1027: in _find_and_load
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
#7 2.313     ???
#7 2.313 <frozen importlib._bootstrap>:688: in _load_unlocked
#7 2.313     ???
#7 2.313 /usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:184: in exec_module
#7 2.313     exec(co, module.__dict__)
#7 2.313 tests/unit/models/core/conftest.py:5: in <module>
#7 2.313     from neo4j_runway.utils.data.data_dictionary.column import Column
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _ ERROR collecting tests/unit/models/solutions_workbench/test_solutions_workbench_data_model.py _
#7 2.313 ImportError while importing test module '/repo/tests/unit/models/solutions_workbench/test_solutions_workbench_data_model.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/models/solutions_workbench/test_solutions_workbench_data_model.py:5: in <module>
#7 2.313     from neo4j_runway.models import (
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _ ERROR collecting tests/unit/models/solutions_workbench/test_solutions_workbench_node.py _
#7 2.313 ImportError while importing test module '/repo/tests/unit/models/solutions_workbench/test_solutions_workbench_node.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/models/solutions_workbench/test_solutions_workbench_node.py:3: in <module>
#7 2.313     from neo4j_runway.models import Node, Property
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _ ERROR collecting tests/unit/models/solutions_workbench/test_solutions_workbench_property.py _
#7 2.313 ImportError while importing test module '/repo/tests/unit/models/solutions_workbench/test_solutions_workbench_property.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/models/solutions_workbench/test_solutions_workbench_property.py:3: in <module>
#7 2.313     from neo4j_runway.models import Property
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _ ERROR collecting tests/unit/models/solutions_workbench/test_solutions_workbench_relationship.py _
#7 2.313 ImportError while importing test module '/repo/tests/unit/models/solutions_workbench/test_solutions_workbench_relationship.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/models/solutions_workbench/test_solutions_workbench_relationship.py:3: in <module>
#7 2.313     from neo4j_runway.models import Property, Relationship
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _ ERROR collecting tests/unit/resources/prompts/data_modeling/test_data_model_prompt_template.py _
#7 2.313 ImportError while importing test module '/repo/tests/unit/resources/prompts/data_modeling/test_data_model_prompt_template.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/resources/prompts/data_modeling/test_data_model_prompt_template.py:1: in <module>
#7 2.313     from neo4j_runway.resources.prompts.data_modeling.template import (
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _ ERROR collecting tests/unit/resources/prompts/data_modeling/test_formatter.py _
#7 2.313 ImportError while importing test module '/repo/tests/unit/resources/prompts/data_modeling/test_formatter.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/resources/prompts/data_modeling/test_formatter.py:1: in <module>
#7 2.313     from neo4j_runway.resources.prompts.data_modeling.formatters import (
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _________ ERROR collecting tests/unit/utils/_utils/test_dictionary.py __________
#7 2.313 ImportError while importing test module '/repo/tests/unit/utils/_utils/test_dictionary.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/utils/_utils/test_dictionary.py:1: in <module>
#7 2.313     from neo4j_runway.utils._utils.dictionary import get_dictionary_depth
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 ____ ERROR collecting tests/unit/utils/data/data_dictionary/test_column.py _____
#7 2.313 ImportError while importing test module '/repo/tests/unit/utils/data/data_dictionary/test_column.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/utils/data/data_dictionary/test_column.py:5: in <module>
#7 2.313     from neo4j_runway.utils.data.data_dictionary.column import Column
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _ ERROR collecting tests/unit/utils/data/data_dictionary/test_data_dictionary.py _
#7 2.313 ImportError while importing test module '/repo/tests/unit/utils/data/data_dictionary/test_data_dictionary.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/utils/data/data_dictionary/test_data_dictionary.py:3: in <module>
#7 2.313     from neo4j_runway.utils.data.data_dictionary.data_dictionary import DataDictionary
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _ ERROR collecting tests/unit/utils/data/data_dictionary/test_data_dictionary_utils.py _
#7 2.313 ImportError while importing test module '/repo/tests/unit/utils/data/data_dictionary/test_data_dictionary_utils.py'.
#7 2.313 Hint: make sure your test modules/packages have valid Python names.
#7 2.313 Traceback:
#7 2.313 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.313     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.313 tests/unit/utils/data/data_dictionary/test_data_dictionary_utils.py:1: in <module>
#7 2.313     from neo4j_runway.utils.data import (
#7 2.313 neo4j_runway/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.313     from .discovery import Discovery
#7 2.313 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.313     import pandas as pd
#7 2.313 E   ModuleNotFoundError: No module named 'pandas'
#7 2.313 _ ERROR collecting tests/unit/utils/data/data_dictionary/test_table_schema.py __
#7 2.316 ImportError while importing test module '/repo/tests/unit/utils/data/data_dictionary/test_table_schema.py'.
#7 2.316 Hint: make sure your test modules/packages have valid Python names.
#7 2.316 Traceback:
#7 2.316 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.316     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.316 tests/unit/utils/data/data_dictionary/test_table_schema.py:5: in <module>
#7 2.316     from neo4j_runway.utils.data.data_dictionary.column import Column
#7 2.316 neo4j_runway/__init__.py:1: in <module>
#7 2.316     from .discovery import Discovery
#7 2.316 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.316     from .discovery import Discovery
#7 2.316 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.316     import pandas as pd
#7 2.316 E   ModuleNotFoundError: No module named 'pandas'
#7 2.316 __________ ERROR collecting tests/unit/utils/data/test_data_loader.py __________
#7 2.316 ImportError while importing test module '/repo/tests/unit/utils/data/test_data_loader.py'.
#7 2.316 Hint: make sure your test modules/packages have valid Python names.
#7 2.316 Traceback:
#7 2.316 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.316     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.316 tests/unit/utils/data/test_data_loader.py:3: in <module>
#7 2.316     import pandas as pd
#7 2.316 E   ModuleNotFoundError: No module named 'pandas'
#7 2.316 _____________ ERROR collecting tests/unit/utils/data/test_table.py _____________
#7 2.316 ImportError while importing test module '/repo/tests/unit/utils/data/test_table.py'.
#7 2.316 Hint: make sure your test modules/packages have valid Python names.
#7 2.316 Traceback:
#7 2.316 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.316     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.316 tests/unit/utils/data/test_table.py:1: in <module>
#7 2.316     import pandas as pd
#7 2.316 E   ModuleNotFoundError: No module named 'pandas'
#7 2.316 _________ ERROR collecting tests/unit/utils/test_naming_conventions.py _________
#7 2.316 ImportError while importing test module '/repo/tests/unit/utils/test_naming_conventions.py'.
#7 2.316 Hint: make sure your test modules/packages have valid Python names.
#7 2.316 Traceback:
#7 2.316 /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
#7 2.316     return _bootstrap._gcd_import(name[level:], package, level)
#7 2.316 tests/unit/utils/test_naming_conventions.py:3: in <module>
#7 2.316     from neo4j_runway.utils.naming_conventions import (
#7 2.316 neo4j_runway/__init__.py:1: in <module>
#7 2.316     from .discovery import Discovery
#7 2.316 neo4j_runway/discovery/__init__.py:1: in <module>
#7 2.316     from .discovery import Discovery
#7 2.316 neo4j_runway/discovery/discovery.py:10: in <module>
#7 2.316     import pandas as pd
#7 2.316 E   ModuleNotFoundError: No module named 'pandas'
#7 2.316 =========================== short test summary info ============================
#7 2.316 ERROR neo4j_runway/utils/test_connection.py
#7 2.316 ERROR tests/integration/code_generation/load_csv/test_load_csv_via_api_IT.py
#7 2.316 ERROR tests/integration/code_generation/load_csv/test_load_csv_via_api_multi_csv_IT.py
#7 2.316 ERROR tests/integration/code_generation/load_csv/test_load_csv_via_api_multi_csv_and_same_node_rel_IT.py
#7 2.316 ERROR tests/integration/code_generation/load_csv/test_load_csv_via_api_node_keys_IT.py
#7 2.316 ERROR tests/integration/database/test_neo4j_graph_IT.py
#7 2.316 ERROR tests/integration/discovery - ModuleNotFoundError: No module named 'pan...
#7 2.316 ERROR tests/integration/graph_eda - ModuleNotFoundError: No module named 'neo4j'
#7 2.316 ERROR tests/integration/ingestion/test_pyingest_dataframe_IT.py
#7 2.316 ERROR tests/integration/ingestion/test_pyingest_multi_csv_IT.py
#7 2.316 ERROR tests/integration/ingestion/test_pyingest_post_ingestion_IT.py
#7 2.316 ERROR tests/integration/modeler - ModuleNotFoundError: No module named 'pandas'
#7 2.316 ERROR tests/integration/utils/data - ModuleNotFoundError: No module named 'pa...
#7 2.316 ERROR tests/unit/code_generation/cypher/test_cypher_generation.py
#7 2.316 ERROR tests/unit/code_generation/cypher/test_cypher_generation_class.py
#7 2.316 ERROR tests/unit/code_generation/load_csv/test_load_csv_generation.py
#7 2.316 ERROR tests/unit/code_generation/pyingest/test_pyingest_generation_multi_csv.py
#7 2.316 ERROR tests/unit/code_generation/pyingest/test_pyingest_generation_wht_params.py
#7 2.316 ERROR tests/unit/code_generation/pyingest/test_pyingest_generation_with_params.py
#7 2.316 ERROR tests/unit/code_generation/pyingest/test_pyingest_post_ingest_input.py
#7 2.316 ERROR tests/unit/code_generation/pyingest/test_pyingest_pre_ingest_input.py
#7 2.316 ERROR tests/unit/code_generation/standard/test_standard_code_generator.py
#7 2.316 ERROR tests/unit/discovery - ModuleNotFoundError: No module named 'pandas'
#7 2.316 ERROR tests/unit/graph_eda - ModuleNotFoundError: No module named 'pandas'
#7 2.316 ERROR tests/unit/inputs/test_user_input.py
#7 2.316 ERROR tests/unit/llm/test_context.py
#7 2.316 ERROR tests/unit/modeler - ModuleNotFoundError: No module named 'pandas'
#7 2.316 ERROR tests/unit/models/arrows/test_arrows_data_model.py
#7 2.316 ERROR tests/unit/models/core - ModuleNotFoundError: No module named 'pandas'
#7 2.316 ERROR tests/unit/models/solutions_workbench/test_solutions_workbench_data_model.py
#7 2.316 ERROR tests/unit/models/solutions_workbench/test_solutions_workbench_node.py
#7 2.316 ERROR tests/unit/models/solutions_workbench/test_solutions_workbench_property.py
#7 2.316 ERROR tests/unit/models/solutions_workbench/test_solutions_workbench_relationship.py
#7 2.316 ERROR tests/unit/resources/prompts/data_modeling/test_data_model_prompt_template.py
#7 2.316 ERROR tests/unit/resources/prompts/data_modeling/test_formatter.py
#7 2.316 ERROR tests/unit/utils/_utils/test_dictionary.py
#7 2.316 ERROR tests/unit/utils/data/data_dictionary/test_column.py
#7 2.316 ERROR tests/unit/utils/data/data_dictionary/test_data_dictionary.py
#7 2.316 ERROR tests/unit/utils/data/data_dictionary/test_data_dictionary_utils.py
#7 2.316 ERROR tests/unit/utils/data/data_dictionary/test_table_schema.py
#7 2.316 ERROR tests/unit/utils/data/test_data_loader.py
#7 2.316 ERROR tests/unit/utils/data/test_table.py
#7 2.316 ERROR tests/unit/utils/test_naming_conventions.py
#7 2.316 !!!!!!!!!!!!!!!!!!! Interrupted: 43 errors during collection !!!!!!!!!!!!!!!!!!!
#7 2.316 no tests collected, 43 errors in 1.55s
#7 ERROR: process "/bin/sh -c cd /repo && pytest --collect-only -q" did not complete successfully: exit code: 2
------
 > [4/5] RUN cd /repo && pytest --collect-only -q:
2.316 ERROR tests/unit/utils/_utils/test_dictionary.py
2.316 ERROR tests/unit/utils/data/data_dictionary/test_column.py
2.316 ERROR tests/unit/utils/data/data_dictionary/test_data_dictionary.py
2.316 ERROR tests/unit/utils/data/data_dictionary/test_data_dictionary_utils.py
2.316 ERROR tests/unit/utils/data/data_dictionary/test_table_schema.py
2.316 ERROR tests/unit/utils/data/test_data_loader.py
2.316 ERROR tests/unit/utils/data/test_table.py
2.316 ERROR tests/unit/utils/test_naming_conventions.py
2.316 !!!!!!!!!!!!!!!!!!! Interrupted: 43 errors during collection !!!!!!!!!!!!!!!!!!!
2.316 no tests collected, 43 errors in 1.55s
------
Dockerfile:20
--------------------
  18 |         cd /repo && git checkout 16b44177d434465f7fbeef59273444c963343726 && \
  19 |         cd /repo && poetry install
  20 | >>> RUN cd /repo && pytest --collect-only -q
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /repo && pytest --collect-only -q" did not complete successfully: exit code: 2
